Fix one of the calculateNextTree errors
Still got this problem
```
Error: dt.sml 77.23-77.39.
  Function applied to incorrect argument.
    expects: [real array * real] list
    but got: [real] list
    in: C.train residuals
Error: dt.sml 79.16-79.35.
  Function applied to incorrect argument.
    expects: [D.t] list
    but got: [real * D.t] list
    in: findBest prunedTrees

```